### ISSUE TITLE
Maybe there misses some files?

### ISSUE THREAD

**Issue by IMIMyzj** [IfA/CMR_Simulation#1]
No function or variable is defined 'filter_slam2d'。

error filter_ddrive_ekf (line 5)
    filter = filter_slam2d(@filterStep); % reuse drawing function from generic localization2d block

error exp_ekf_ddrive (line 67)
    exp.robot.localization = filter_ddrive_ekf();

**Comment by chaolmu** [comment]
thanks for your notification. the correct file is uploaded.
